version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: nuturing
    container_name: nuturing-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - nuturing
    environment:
      APP_ENV: production
      DB_CONNECTION: mysql
      DB_HOST: ${DB_HOST} # Online database host
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  nginx:
    image: nginx:alpine
    container_name: nuturing-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - nuturing

networks:
  nuturing:
    driver: bridge
